In [61]:
# импорт

%matplotlib inline
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats
import os
dir = os.path.abspath(os.curdir)
dir

'/home/jovyan/demo'

In [149]:
from sklearn import tree
from sklearn.cluster import KMeans
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [132]:
# загружаем файлы

train_my_1 = pd.read_excel('/home/jovyan/demo/data/credit_train_my_data_1.xlsx')

In [136]:
train_my_2 = pd.read_excel('/home/jovyan/demo/data/credit_train_my_data_2.xlsx')

In [139]:
# Information Value

Information_Value = pd.DataFrame()
attr_bins

column_list = list(train_my_2)
j = -1

for col_name in column_list:
    
    j = j + 1
    
    if (col_name == 'EVENT' or col_name == 'HELP'):
        continue
        
    #if (col_name != 'Credit_Score'):
    #    continue
        
    attr_bins = train_my_1.groupby(col_name,as_index = False) \
                              .aggregate({'HELP' : 'count', 
                                          'EVENT' : 'sum'}) \
                              .rename(columns = {col_name : col_name,
                                                 'HELP':'ALL_OBS',
                                                 'EVENT':'GOOD_OBS'}) \
                              .sort_values(col_name, ascending=True)
    
    attr_bins = attr_bins.assign(BAD_OBS = attr_bins.ALL_OBS - attr_bins.GOOD_OBS,
                                 del_flag = 0)
    
    # склеивание бинов
    
    this_bin  = -1
    this_all  = -1
    this_good = -1
    this_bad  = -1
    last_bin  = -1
    last_all  = -1
    last_good = -1
    last_bad  = -1
    
    i = -1
    
    for index, row in attr_bins.iterrows():
        
        i = i + 1
              
        if this_all != -1:
            
            last_bin  = this_bin
            last_all  = this_all
            last_good = this_good
            last_bad  = this_bad
        
        this_bin  = row[col_name]
        this_all  = row['ALL_OBS']
        this_good = row['GOOD_OBS']
        this_bad  = row['BAD_OBS']               
        
        if this_bin != 1 and ((this_good == 0 or this_bad == 0) or (last_good == 0 or last_bad == 0)): 
            
            attr_bins.loc[i,'del_flag'] = 1
            attr_bins.loc[i-1,'del_flag'] = 1
            
            was_bin   = this_bin
            this_bin  = (this_bin + last_bin)/2
            this_all  = this_all + last_all
            this_good = this_good + last_good
            this_bad  = this_bad + last_bad

            attr_bins = attr_bins.append(pd.DataFrame([[this_bin, 
                                                        this_all,
                                                        this_good,
                                                        this_bad,
                                                        0]], 
                                                        columns=[col_name, 'ALL_OBS', 'GOOD_OBS', 'BAD_OBS', 'del_flag']),
                                         ignore_index=True, sort = False)                       

    #attr_bins = attr_bins.query('del_flag == 0')                     
    #attr_bins = attr_bins.query('GOOD_OBS != 0')          
    #attr_bins = attr_bins.query('BAD_OBS != 0')
        
    attr_bins = attr_bins.sort_values(col_name, ascending=True)
            
    SUM_GOOD_OBS = attr_bins.GOOD_OBS.sum()
    SUM_BAD_OBS = attr_bins.BAD_OBS.sum()
    
    attr_bins = attr_bins.assign(GOOD_PRCNT = attr_bins.GOOD_OBS/SUM_GOOD_OBS,
                                 BAD_PRCNT  = attr_bins.BAD_OBS/SUM_BAD_OBS)
    
    
    attr_bins = attr_bins.assign(WOE = np.log(attr_bins.GOOD_PRCNT/attr_bins.BAD_PRCNT))
    attr_bins = attr_bins.assign(IV  = (attr_bins.GOOD_PRCNT - attr_bins.BAD_PRCNT) * attr_bins.WOE)
    
    #print(attr_bins)
    
    SUM_IV = attr_bins.IV.sum()

    temp_IV = pd.DataFrame({'index' : [j],
                            'name': [col_name],
                            'IV': [round(SUM_IV,5)]})
    
    Information_Value = Information_Value.append(temp_IV, sort=False)
    
Information_Value = Information_Value.set_index('index').reset_index(drop=True)

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:91: RuntimeWarning: divide by zero encountered in log

In [140]:
Information_Value.sort_values('IV', ascending=False)

                  name       IV
2     Credit_Score_FLG      inf
0  Current_Loan_Amount  0.42681
3         Credit_Score  0.19533
1                 Term  0.13274
4        Annual_Income  0.04739
6  Maximum_Open_Credit  0.02127
5       Home_Ownership  0.01969

In [143]:
# P_Value

PVALUE_cl_5_two = train_my_1.drop(['EVENT', 'HELP','Purpose'], axis=1).values
PVALUE_RESULT = stats.ttest_1samp(PVALUE_cl_5_two,5.0)
PVALUE_DF = pd.DataFrame(PVALUE_RESULT[1], columns=['P_VALUE'])
MODEL_RESULTS = Information_Value.join(PVALUE_DF)
#MODEL_RESULTS = MODEL_RESULTS.query('IV > 0.019')
#MODEL_RESULTS = MODEL_RESULTS.query('IV < 2.5')
MODEL_RESULTS = MODEL_RESULTS.query('P_VALUE < 0.005')

MODEL_RESULTS

                  name       IV  P_VALUE
0  Current_Loan_Amount  0.42681      0.0
1                 Term  0.13274      0.0
2     Credit_Score_FLG      inf      0.0
3         Credit_Score  0.19533      0.0
4        Annual_Income  0.04739      0.0
5       Home_Ownership  0.01969      0.0
6  Maximum_Open_Credit  0.02127      0.0

In [151]:
# регрессия

X_regr = train_my_2.drop(['EVENT'], axis=1)
Y_regr = train_my_2['EVENT']

REGRESSION_DF = pd.DataFrame()

x_train_regr, x_test_regr, y_train_regr, y_test_regr = train_test_split(X_regr, Y_regr, test_size=0.3)

regr_1 = LinearRegression()
regr_2 = RandomForestRegressor(n_estimators=100, max_features ='sqrt')
regr_3 = KNeighborsRegressor(n_neighbors=6)
regr_4 = SVR(kernel='linear')
regr_5 = LogisticRegression(solver = 'lbfgs')

#regr_1.fit(x_train_regr, y_train_regr)
#regr_2.fit(x_train_regr, y_train_regr)
#regr_3.fit(x_train_regr, y_train_regr)
#regr_4.fit(x_train_regr, y_train_regr)
regr_5.fit(x_train_regr, y_train_regr)

#temp_regr_1 = pd.DataFrame({'name': ['LinearRegression'],
#                          'train R^2': [regr_1.score(x_train_regr, y_train_regr)],
#                          'test R^2' : [regr_1.score(x_test_regr, y_test_regr)]})

#temp_regr_2 = pd.DataFrame({'name': ['RandomForestRegressor'],
#                          'train R^2': [regr_2.score(x_train_regr, y_train_regr)],
#                          'test R^2' : [regr_2.score(x_test_regr, y_test_regr)]})

#temp_regr_3 = pd.DataFrame({'name': ['KNeighborsRegressor'],
#                          'train R^2': [regr_3.score(x_train_regr, y_train_regr)],
#                          'test R^2' : [regr_3.score(x_test_regr, y_test_regr)]})

#temp_regr_4 = pd.DataFrame({'name': ['SVR'],
#                          'train R^2': [regr_4.score(x_train_regr, y_train_regr)],
#                          'test R^2' : [regr_4.score(x_test_regr, y_test_regr)]})

temp_regr_5 = pd.DataFrame({'name': ['LogisticRegression'],
                          'train R^2': [regr_5.score(x_train_regr, y_train_regr)],
                          'test R^2' : [regr_5.score(x_test_regr, y_test_regr)]})

#REGRESSION_DF = REGRESSION_DF.append(temp_regr_1, sort=False)
#REGRESSION_DF = REGRESSION_DF.append(temp_regr_2, sort=False)
#REGRESSION_DF = REGRESSION_DF.append(temp_regr_3, sort=False)
#REGRESSION_DF = REGRESSION_DF.append(temp_regr_4, sort=False)
REGRESSION_DF = REGRESSION_DF.append(temp_regr_5, sort=False)

In [152]:
REGRESSION_DF

                 name  train R^2  test R^2
0  LogisticRegression   0.779317  0.781545